version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file: ".env"
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ~/apps/postgres_bridge:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
