/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace UsersStruct {
  export type BusinessValueStruct = {
    left: BigNumberish;
    right: BigNumberish;
    dir: BigNumberish;
    level: BigNumberish;
    summ: BigNumberish;
  };

  export type BusinessValueStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    left: BigNumber;
    right: BigNumber;
    dir: BigNumber;
    level: BigNumber;
    summ: BigNumber;
  };

  export type LastOrderStruct = {
    date: BigNumberish;
    order_id: BigNumberish;
    bv_level: BigNumberish;
  };

  export type LastOrderStructOutput = [BigNumber, BigNumber, BigNumber] & {
    date: BigNumber;
    order_id: BigNumber;
    bv_level: BigNumber;
  };

  export type UserStruct = {
    id: BigNumberish;
    bv: UsersStruct.BusinessValueStruct;
    last_order: UsersStruct.LastOrderStruct;
    depth: BigNumberish;
    pending_withdraw: BigNumberish;
    levelup_count: BigNumberish;
    lastweek: BigNumberish;
    step: BigNumberish;
    pending_voucher: BigNumberish;
    exists: boolean;
    data: BytesLike;
  };

  export type UserStructOutput = [
    BigNumber,
    UsersStruct.BusinessValueStructOutput,
    UsersStruct.LastOrderStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    string
  ] & {
    id: BigNumber;
    bv: UsersStruct.BusinessValueStructOutput;
    last_order: UsersStruct.LastOrderStructOutput;
    depth: BigNumber;
    pending_withdraw: BigNumber;
    levelup_count: BigNumber;
    lastweek: BigNumber;
    step: BigNumber;
    pending_voucher: BigNumber;
    exists: boolean;
    data: string;
  };
}

export interface UsersStructInterface extends utils.Interface {
  functions: {
    "BVPlan(uint256)": FunctionFragment;
    "ListLevelUpDate(uint256)": FunctionFragment;
    "UserAddress(uint256)": FunctionFragment;
    "UserLevelUpDateIndex(uint256,uint256)": FunctionFragment;
    "UserList(address)": FunctionFragment;
    "UsersPaths(uint256,uint256)": FunctionFragment;
    "UsersPathsHash(uint256,uint256)": FunctionFragment;
    "getUser(address)": FunctionFragment;
    "level_up_data_index()": FunctionFragment;
    "user_id()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BVPlan"
      | "ListLevelUpDate"
      | "UserAddress"
      | "UserLevelUpDateIndex"
      | "UserList"
      | "UsersPaths"
      | "UsersPathsHash"
      | "getUser"
      | "level_up_data_index"
      | "user_id"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BVPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ListLevelUpDate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "UserAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "UserLevelUpDateIndex",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "UserList", values: [string]): string;
  encodeFunctionData(
    functionFragment: "UsersPaths",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "UsersPathsHash",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getUser", values: [string]): string;
  encodeFunctionData(
    functionFragment: "level_up_data_index",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "user_id", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BVPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ListLevelUpDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UserAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UserLevelUpDateIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UserList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "UsersPaths", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UsersPathsHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "level_up_data_index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "user_id", data: BytesLike): Result;

  events: {};
}

export interface UsersStruct extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UsersStructInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BVPlan(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    ListLevelUpDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { date: BigNumber; level: BigNumber }>;

    UserAddress(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    UserLevelUpDateIndex(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    UserList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        UsersStruct.BusinessValueStructOutput,
        UsersStruct.LastOrderStructOutput,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        string
      ] & {
        id: BigNumber;
        bv: UsersStruct.BusinessValueStructOutput;
        last_order: UsersStruct.LastOrderStructOutput;
        depth: BigNumber;
        pending_withdraw: BigNumber;
        levelup_count: BigNumber;
        lastweek: BigNumber;
        step: BigNumber;
        pending_voucher: BigNumber;
        exists: boolean;
        data: string;
      }
    >;

    UsersPaths(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    UsersPathsHash(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUser(
      user_address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    level_up_data_index(overrides?: CallOverrides): Promise<[BigNumber]>;

    user_id(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  BVPlan(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  ListLevelUpDate(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { date: BigNumber; level: BigNumber }>;

  UserAddress(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  UserLevelUpDateIndex(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  UserList(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      UsersStruct.BusinessValueStructOutput,
      UsersStruct.LastOrderStructOutput,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      string
    ] & {
      id: BigNumber;
      bv: UsersStruct.BusinessValueStructOutput;
      last_order: UsersStruct.LastOrderStructOutput;
      depth: BigNumber;
      pending_withdraw: BigNumber;
      levelup_count: BigNumber;
      lastweek: BigNumber;
      step: BigNumber;
      pending_voucher: BigNumber;
      exists: boolean;
      data: string;
    }
  >;

  UsersPaths(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  UsersPathsHash(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getUser(
    user_address: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  level_up_data_index(overrides?: CallOverrides): Promise<BigNumber>;

  user_id(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    BVPlan(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    ListLevelUpDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { date: BigNumber; level: BigNumber }>;

    UserAddress(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    UserLevelUpDateIndex(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    UserList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        UsersStruct.BusinessValueStructOutput,
        UsersStruct.LastOrderStructOutput,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        string
      ] & {
        id: BigNumber;
        bv: UsersStruct.BusinessValueStructOutput;
        last_order: UsersStruct.LastOrderStructOutput;
        depth: BigNumber;
        pending_withdraw: BigNumber;
        levelup_count: BigNumber;
        lastweek: BigNumber;
        step: BigNumber;
        pending_voucher: BigNumber;
        exists: boolean;
        data: string;
      }
    >;

    UsersPaths(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    UsersPathsHash(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getUser(
      user_address: string,
      overrides?: CallOverrides
    ): Promise<UsersStruct.UserStructOutput>;

    level_up_data_index(overrides?: CallOverrides): Promise<BigNumber>;

    user_id(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    BVPlan(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    ListLevelUpDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    UserAddress(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    UserLevelUpDateIndex(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    UserList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    UsersPaths(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    UsersPathsHash(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUser(
      user_address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    level_up_data_index(overrides?: CallOverrides): Promise<BigNumber>;

    user_id(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BVPlan(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ListLevelUpDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UserAddress(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UserLevelUpDateIndex(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UserList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UsersPaths(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UsersPathsHash(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUser(
      user_address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    level_up_data_index(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    user_id(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
