/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helperTSol from "./Helper.t.sol";
export type { helperTSol };
import type * as setupSol from "./Setup.sol";
export type { setupSol };
