/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace StdInvariant {
  export type FuzzSelectorStruct = { addr: string; selectors: BytesLike[] };

  export type FuzzSelectorStructOutput = [string, string[]] & {
    addr: string;
    selectors: string[];
  };

  export type FuzzInterfaceStruct = { addr: string; artifacts: string[] };

  export type FuzzInterfaceStructOutput = [string, string[]] & {
    addr: string;
    artifacts: string[];
  };
}

export interface StakeTestInterface extends utils.Interface {
  functions: {
    "IS_TEST()": FunctionFragment;
    "baseCalculateRewardTest(uint16,uint256,uint256,uint256)": FunctionFragment;
    "dnmToken()": FunctionFragment;
    "excludeArtifacts()": FunctionFragment;
    "excludeContracts()": FunctionFragment;
    "excludeSenders()": FunctionFragment;
    "failed()": FunctionFragment;
    "nftLand()": FunctionFragment;
    "sc()": FunctionFragment;
    "setUp()": FunctionFragment;
    "stake()": FunctionFragment;
    "targetArtifactSelectors()": FunctionFragment;
    "targetArtifacts()": FunctionFragment;
    "targetContracts()": FunctionFragment;
    "targetInterfaces()": FunctionFragment;
    "targetSelectors()": FunctionFragment;
    "targetSenders()": FunctionFragment;
    "test12CalBonusPlan1()": FunctionFragment;
    "test12CalBonusPlan2()": FunctionFragment;
    "test12CalBonusPlan3()": FunctionFragment;
    "test12CalBonusPlan4()": FunctionFragment;
    "test12CalBonusPlan5()": FunctionFragment;
    "test18CalBonusPlan1()": FunctionFragment;
    "test18CalBonusPlan2()": FunctionFragment;
    "test18CalBonusPlan3()": FunctionFragment;
    "test18CalBonusPlan4()": FunctionFragment;
    "test18CalBonusPlan5()": FunctionFragment;
    "test24CalBonusPlan1()": FunctionFragment;
    "test24CalBonusPlan2()": FunctionFragment;
    "test24CalBonusPlan3()": FunctionFragment;
    "test24CalBonusPlan4()": FunctionFragment;
    "test24CalBonusPlan5()": FunctionFragment;
    "testCheckBalance()": FunctionFragment;
    "testPlanValidation()": FunctionFragment;
    "testRatio()": FunctionFragment;
    "testStake4AndRemoveSideContract()": FunctionFragment;
    "testStakeCycle1()": FunctionFragment;
    "testStakeCycle2()": FunctionFragment;
    "testStakeCycle3()": FunctionFragment;
    "testStakeFirstValidation()": FunctionFragment;
    "testStakeFrom()": FunctionFragment;
    "testTokensState()": FunctionFragment;
    "testWithPrankedAddress()": FunctionFragment;
    "uvmToken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_TEST"
      | "baseCalculateRewardTest"
      | "dnmToken"
      | "excludeArtifacts"
      | "excludeContracts"
      | "excludeSenders"
      | "failed"
      | "nftLand"
      | "sc"
      | "setUp"
      | "stake"
      | "targetArtifactSelectors"
      | "targetArtifacts"
      | "targetContracts"
      | "targetInterfaces"
      | "targetSelectors"
      | "targetSenders"
      | "test12CalBonusPlan1"
      | "test12CalBonusPlan2"
      | "test12CalBonusPlan3"
      | "test12CalBonusPlan4"
      | "test12CalBonusPlan5"
      | "test18CalBonusPlan1"
      | "test18CalBonusPlan2"
      | "test18CalBonusPlan3"
      | "test18CalBonusPlan4"
      | "test18CalBonusPlan5"
      | "test24CalBonusPlan1"
      | "test24CalBonusPlan2"
      | "test24CalBonusPlan3"
      | "test24CalBonusPlan4"
      | "test24CalBonusPlan5"
      | "testCheckBalance"
      | "testPlanValidation"
      | "testRatio"
      | "testStake4AndRemoveSideContract"
      | "testStakeCycle1"
      | "testStakeCycle2"
      | "testStakeCycle3"
      | "testStakeFirstValidation"
      | "testStakeFrom"
      | "testTokensState"
      | "testWithPrankedAddress"
      | "uvmToken"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseCalculateRewardTest",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dnmToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "excludeArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeSenders",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(functionFragment: "nftLand", values?: undefined): string;
  encodeFunctionData(functionFragment: "sc", values?: undefined): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(functionFragment: "stake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "targetArtifactSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetInterfaces",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSenders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test12CalBonusPlan1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test12CalBonusPlan2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test12CalBonusPlan3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test12CalBonusPlan4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test12CalBonusPlan5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test18CalBonusPlan1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test18CalBonusPlan2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test18CalBonusPlan3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test18CalBonusPlan4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test18CalBonusPlan5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test24CalBonusPlan1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test24CalBonusPlan2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test24CalBonusPlan3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test24CalBonusPlan4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test24CalBonusPlan5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCheckBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testPlanValidation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "testRatio", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testStake4AndRemoveSideContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testStakeCycle1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testStakeCycle2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testStakeCycle3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testStakeFirstValidation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testStakeFrom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testTokensState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testWithPrankedAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "uvmToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseCalculateRewardTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dnmToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "excludeArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nftLand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifactSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetInterfaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test12CalBonusPlan1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test12CalBonusPlan2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test12CalBonusPlan3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test12CalBonusPlan4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test12CalBonusPlan5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test18CalBonusPlan1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test18CalBonusPlan2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test18CalBonusPlan3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test18CalBonusPlan4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test18CalBonusPlan5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test24CalBonusPlan1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test24CalBonusPlan2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test24CalBonusPlan3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test24CalBonusPlan4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test24CalBonusPlan5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCheckBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testPlanValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testRatio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testStake4AndRemoveSideContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testStakeCycle1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testStakeCycle2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testStakeCycle3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testStakeFirstValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testStakeFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testTokensState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testWithPrankedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uvmToken", data: BytesLike): Result;

  events: {
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_array(uint256[])": EventFragment;
    "log_array(int256[])": EventFragment;
    "log_array(address[])": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_array(string,uint256[])": EventFragment;
    "log_named_array(string,int256[])": EventFragment;
    "log_named_array(string,address[])": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(uint256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(int256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(address[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,uint256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,int256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,address[])"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export interface logEventObject {
  arg0: string;
}
export type logEvent = TypedEvent<[string], logEventObject>;

export type logEventFilter = TypedEventFilter<logEvent>;

export interface log_addressEventObject {
  arg0: string;
}
export type log_addressEvent = TypedEvent<[string], log_addressEventObject>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export interface log_array_uint256_array_EventObject {
  val: BigNumber[];
}
export type log_array_uint256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_uint256_array_EventObject
>;

export type log_array_uint256_array_EventFilter =
  TypedEventFilter<log_array_uint256_array_Event>;

export interface log_array_int256_array_EventObject {
  val: BigNumber[];
}
export type log_array_int256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_int256_array_EventObject
>;

export type log_array_int256_array_EventFilter =
  TypedEventFilter<log_array_int256_array_Event>;

export interface log_array_address_array_EventObject {
  val: string[];
}
export type log_array_address_array_Event = TypedEvent<
  [string[]],
  log_array_address_array_EventObject
>;

export type log_array_address_array_EventFilter =
  TypedEventFilter<log_array_address_array_Event>;

export interface log_bytesEventObject {
  arg0: string;
}
export type log_bytesEvent = TypedEvent<[string], log_bytesEventObject>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export interface log_bytes32EventObject {
  arg0: string;
}
export type log_bytes32Event = TypedEvent<[string], log_bytes32EventObject>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export interface log_intEventObject {
  arg0: BigNumber;
}
export type log_intEvent = TypedEvent<[BigNumber], log_intEventObject>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export interface log_named_addressEventObject {
  key: string;
  val: string;
}
export type log_named_addressEvent = TypedEvent<
  [string, string],
  log_named_addressEventObject
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export interface log_named_array_string_uint256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_uint256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_uint256_array_EventObject
>;

export type log_named_array_string_uint256_array_EventFilter =
  TypedEventFilter<log_named_array_string_uint256_array_Event>;

export interface log_named_array_string_int256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_int256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_int256_array_EventObject
>;

export type log_named_array_string_int256_array_EventFilter =
  TypedEventFilter<log_named_array_string_int256_array_Event>;

export interface log_named_array_string_address_array_EventObject {
  key: string;
  val: string[];
}
export type log_named_array_string_address_array_Event = TypedEvent<
  [string, string[]],
  log_named_array_string_address_array_EventObject
>;

export type log_named_array_string_address_array_EventFilter =
  TypedEventFilter<log_named_array_string_address_array_Event>;

export interface log_named_bytesEventObject {
  key: string;
  val: string;
}
export type log_named_bytesEvent = TypedEvent<
  [string, string],
  log_named_bytesEventObject
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export interface log_named_bytes32EventObject {
  key: string;
  val: string;
}
export type log_named_bytes32Event = TypedEvent<
  [string, string],
  log_named_bytes32EventObject
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export interface log_named_decimal_intEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_intEventObject
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export interface log_named_decimal_uintEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_uintEventObject
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export interface log_named_intEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  log_named_intEventObject
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export interface log_named_stringEventObject {
  key: string;
  val: string;
}
export type log_named_stringEvent = TypedEvent<
  [string, string],
  log_named_stringEventObject
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export interface log_named_uintEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  log_named_uintEventObject
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export interface log_stringEventObject {
  arg0: string;
}
export type log_stringEvent = TypedEvent<[string], log_stringEventObject>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export interface log_uintEventObject {
  arg0: BigNumber;
}
export type log_uintEvent = TypedEvent<[BigNumber], log_uintEventObject>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export interface logsEventObject {
  arg0: string;
}
export type logsEvent = TypedEvent<[string], logsEventObject>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface StakeTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StakeTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    baseCalculateRewardTest(
      plan: BigNumberish,
      dnm_amount: BigNumberish,
      oneDayBonus: BigNumberish,
      stake_duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    dnmToken(overrides?: CallOverrides): Promise<[string]>;

    excludeArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedArtifacts_: string[] }>;

    excludeContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedContracts_: string[] }>;

    excludeSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedSenders_: string[] }>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    nftLand(overrides?: CallOverrides): Promise<[string]>;

    sc(overrides?: CallOverrides): Promise<[string]>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stake(overrides?: CallOverrides): Promise<[string]>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedArtifactSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedArtifacts_: string[] }>;

    targetContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedContracts_: string[] }>;

    targetInterfaces(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzInterfaceStructOutput[]] & {
        targetedInterfaces_: StdInvariant.FuzzInterfaceStructOutput[];
      }
    >;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedSenders_: string[] }>;

    test12CalBonusPlan1(overrides?: CallOverrides): Promise<[void]>;

    test12CalBonusPlan2(overrides?: CallOverrides): Promise<[void]>;

    test12CalBonusPlan3(overrides?: CallOverrides): Promise<[void]>;

    test12CalBonusPlan4(overrides?: CallOverrides): Promise<[void]>;

    test12CalBonusPlan5(overrides?: CallOverrides): Promise<[void]>;

    test18CalBonusPlan1(overrides?: CallOverrides): Promise<[void]>;

    test18CalBonusPlan2(overrides?: CallOverrides): Promise<[void]>;

    test18CalBonusPlan3(overrides?: CallOverrides): Promise<[void]>;

    test18CalBonusPlan4(overrides?: CallOverrides): Promise<[void]>;

    test18CalBonusPlan5(overrides?: CallOverrides): Promise<[void]>;

    test24CalBonusPlan1(overrides?: CallOverrides): Promise<[void]>;

    test24CalBonusPlan2(overrides?: CallOverrides): Promise<[void]>;

    test24CalBonusPlan3(overrides?: CallOverrides): Promise<[void]>;

    test24CalBonusPlan4(overrides?: CallOverrides): Promise<[void]>;

    test24CalBonusPlan5(overrides?: CallOverrides): Promise<[void]>;

    testCheckBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    testPlanValidation(overrides?: CallOverrides): Promise<[void]>;

    testRatio(overrides?: CallOverrides): Promise<[void]>;

    testStake4AndRemoveSideContract(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testStakeCycle1(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testStakeCycle2(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testStakeCycle3(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testStakeFirstValidation(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testStakeFrom(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    testTokensState(overrides?: CallOverrides): Promise<[void]>;

    testWithPrankedAddress(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    uvmToken(overrides?: CallOverrides): Promise<[string]>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  baseCalculateRewardTest(
    plan: BigNumberish,
    dnm_amount: BigNumberish,
    oneDayBonus: BigNumberish,
    stake_duration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  dnmToken(overrides?: CallOverrides): Promise<string>;

  excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

  excludeContracts(overrides?: CallOverrides): Promise<string[]>;

  excludeSenders(overrides?: CallOverrides): Promise<string[]>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  nftLand(overrides?: CallOverrides): Promise<string>;

  sc(overrides?: CallOverrides): Promise<string>;

  setUp(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stake(overrides?: CallOverrides): Promise<string>;

  targetArtifactSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

  targetContracts(overrides?: CallOverrides): Promise<string[]>;

  targetInterfaces(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzInterfaceStructOutput[]>;

  targetSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetSenders(overrides?: CallOverrides): Promise<string[]>;

  test12CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

  test12CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

  test12CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

  test12CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

  test12CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

  test18CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

  test18CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

  test18CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

  test18CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

  test18CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

  test24CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

  test24CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

  test24CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

  test24CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

  test24CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

  testCheckBalance(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  testPlanValidation(overrides?: CallOverrides): Promise<void>;

  testRatio(overrides?: CallOverrides): Promise<void>;

  testStake4AndRemoveSideContract(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testStakeCycle1(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testStakeCycle2(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testStakeCycle3(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testStakeFirstValidation(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testStakeFrom(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  testTokensState(overrides?: CallOverrides): Promise<void>;

  testWithPrankedAddress(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  uvmToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    baseCalculateRewardTest(
      plan: BigNumberish,
      dnm_amount: BigNumberish,
      oneDayBonus: BigNumberish,
      stake_duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    dnmToken(overrides?: CallOverrides): Promise<string>;

    excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

    excludeContracts(overrides?: CallOverrides): Promise<string[]>;

    excludeSenders(overrides?: CallOverrides): Promise<string[]>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    nftLand(overrides?: CallOverrides): Promise<string>;

    sc(overrides?: CallOverrides): Promise<string>;

    setUp(overrides?: CallOverrides): Promise<void>;

    stake(overrides?: CallOverrides): Promise<string>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

    targetContracts(overrides?: CallOverrides): Promise<string[]>;

    targetInterfaces(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzInterfaceStructOutput[]>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetSenders(overrides?: CallOverrides): Promise<string[]>;

    test12CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

    test12CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

    test12CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

    test12CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

    test12CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

    test18CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

    test18CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

    test18CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

    test18CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

    test18CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

    test24CalBonusPlan1(overrides?: CallOverrides): Promise<void>;

    test24CalBonusPlan2(overrides?: CallOverrides): Promise<void>;

    test24CalBonusPlan3(overrides?: CallOverrides): Promise<void>;

    test24CalBonusPlan4(overrides?: CallOverrides): Promise<void>;

    test24CalBonusPlan5(overrides?: CallOverrides): Promise<void>;

    testCheckBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    testPlanValidation(overrides?: CallOverrides): Promise<void>;

    testRatio(overrides?: CallOverrides): Promise<void>;

    testStake4AndRemoveSideContract(overrides?: CallOverrides): Promise<void>;

    testStakeCycle1(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, string]>;

    testStakeCycle2(overrides?: CallOverrides): Promise<void>;

    testStakeCycle3(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, string, BigNumber]>;

    testStakeFirstValidation(overrides?: CallOverrides): Promise<void>;

    testStakeFrom(overrides?: CallOverrides): Promise<void>;

    testTokensState(overrides?: CallOverrides): Promise<void>;

    testWithPrankedAddress(overrides?: CallOverrides): Promise<void>;

    uvmToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_array(uint256[])"(val?: null): log_array_uint256_array_EventFilter;
    "log_array(int256[])"(val?: null): log_array_int256_array_EventFilter;
    "log_array(address[])"(val?: null): log_array_address_array_EventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_array(string,uint256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_uint256_array_EventFilter;
    "log_named_array(string,int256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_int256_array_EventFilter;
    "log_named_array(string,address[])"(
      key?: null,
      val?: null
    ): log_named_array_string_address_array_EventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    baseCalculateRewardTest(
      plan: BigNumberish,
      dnm_amount: BigNumberish,
      oneDayBonus: BigNumberish,
      stake_duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dnmToken(overrides?: CallOverrides): Promise<BigNumber>;

    excludeArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeContracts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeSenders(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    nftLand(overrides?: CallOverrides): Promise<BigNumber>;

    sc(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    stake(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifactSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    targetContracts(overrides?: CallOverrides): Promise<BigNumber>;

    targetInterfaces(overrides?: CallOverrides): Promise<BigNumber>;

    targetSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetSenders(overrides?: CallOverrides): Promise<BigNumber>;

    test12CalBonusPlan1(overrides?: CallOverrides): Promise<BigNumber>;

    test12CalBonusPlan2(overrides?: CallOverrides): Promise<BigNumber>;

    test12CalBonusPlan3(overrides?: CallOverrides): Promise<BigNumber>;

    test12CalBonusPlan4(overrides?: CallOverrides): Promise<BigNumber>;

    test12CalBonusPlan5(overrides?: CallOverrides): Promise<BigNumber>;

    test18CalBonusPlan1(overrides?: CallOverrides): Promise<BigNumber>;

    test18CalBonusPlan2(overrides?: CallOverrides): Promise<BigNumber>;

    test18CalBonusPlan3(overrides?: CallOverrides): Promise<BigNumber>;

    test18CalBonusPlan4(overrides?: CallOverrides): Promise<BigNumber>;

    test18CalBonusPlan5(overrides?: CallOverrides): Promise<BigNumber>;

    test24CalBonusPlan1(overrides?: CallOverrides): Promise<BigNumber>;

    test24CalBonusPlan2(overrides?: CallOverrides): Promise<BigNumber>;

    test24CalBonusPlan3(overrides?: CallOverrides): Promise<BigNumber>;

    test24CalBonusPlan4(overrides?: CallOverrides): Promise<BigNumber>;

    test24CalBonusPlan5(overrides?: CallOverrides): Promise<BigNumber>;

    testCheckBalance(overrides?: CallOverrides): Promise<BigNumber>;

    testPlanValidation(overrides?: CallOverrides): Promise<BigNumber>;

    testRatio(overrides?: CallOverrides): Promise<BigNumber>;

    testStake4AndRemoveSideContract(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testStakeCycle1(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testStakeCycle2(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testStakeCycle3(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testStakeFirstValidation(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testStakeFrom(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    testTokensState(overrides?: CallOverrides): Promise<BigNumber>;

    testWithPrankedAddress(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    uvmToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseCalculateRewardTest(
      plan: BigNumberish,
      dnm_amount: BigNumberish,
      oneDayBonus: BigNumberish,
      stake_duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dnmToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftLand(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetInterfaces(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSelectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    test12CalBonusPlan1(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test12CalBonusPlan2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test12CalBonusPlan3(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test12CalBonusPlan4(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test12CalBonusPlan5(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test18CalBonusPlan1(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test18CalBonusPlan2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test18CalBonusPlan3(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test18CalBonusPlan4(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test18CalBonusPlan5(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test24CalBonusPlan1(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test24CalBonusPlan2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test24CalBonusPlan3(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test24CalBonusPlan4(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test24CalBonusPlan5(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testCheckBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testPlanValidation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testStake4AndRemoveSideContract(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testStakeCycle1(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testStakeCycle2(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testStakeCycle3(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testStakeFirstValidation(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testStakeFrom(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    testTokensState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testWithPrankedAddress(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    uvmToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
